-- SchemaType: application identity

connect 'jdbc:derby:jdotckdb;create=true' user 'tckuser' password 'tckuser';

CREATE SCHEMA applicationidentity8;
SET SCHEMA applicationidentity8;

DROP TABLE CART_ENTRIES;
DROP TABLE CARTS;
DROP TABLE PRODUCTS;
DROP TABLE UNDETACHABLES;

CREATE TABLE CARTS (
    CART_ID BIGINT NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,

    CONSTRAINT CARTS_PK PRIMARY KEY (CART_ID)
);

CREATE TABLE PRODUCTS (
    SKU VARCHAR(48) NOT NULL,
    DESCRIPTION VARCHAR(128),

    CONSTRAINT PRODUCTS_PK PRIMARY KEY (SKU)
);

CREATE TABLE CART_ENTRIES (
    ID BIGINT NOT NULL,
    CART_ID BIGINT NOT NULL,
    SKU VARCHAR(48) NOT NULL,

    CONSTRAINT CART_ENTRIES_PK  PRIMARY KEY (ID),
    CONSTRAINT CARTS_FK         FOREIGN KEY (CART_ID)   REFERENCES CARTS,
    CONSTRAINT PRODUCTS_FK      FOREIGN KEY (SKU)       REFERENCES PRODUCTS
);

CREATE TABLE UNDETACHABLES (
    ID BIGINT NOT NULL,
    FOO INTEGER,
    BAR INTEGER,

    CONSTRAINT UNDETACHABLES_PK PRIMARY KEY (ID)
);
