-- SchemaType: datastore-identity strategy="identity"

connect 'jdbc:derby:jdotckdb;create=true' user 'tckuser' password 'tckuser';

-------------------------
-- mylib
-------------------------
CREATE TABLE PCPoint (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    X INTEGER NOT NULL,
    Y INTEGER NOT NULL,
    CONSTRAINT PCPNT_CONST PRIMARY KEY (ID)
);

CREATE TABLE PCPoint2 (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    X INTEGER NOT NULL,
    Y INTEGER NOT NULL,
    CONSTRAINT PCPNT2_CONST PRIMARY KEY (ID)
);

CREATE TABLE PCRect (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    UPPER_LEFT INTEGER NOT NULL,
    LOWER_RIGHT INTEGER NOT NULL,
    CONSTRAINT PCRCT_CONST PRIMARY KEY (ID)
);

CREATE TABLE PrimitiveTypes (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    booleanNotNull CHAR FOR BIT DATA NOT NULL,
    booleanNull CHAR FOR BIT DATA NOT NULL,
    byteNotNull SMALLINT NOT NULL,
    byteNull SMALLINT NOT NULL,
    shortNotNull SMALLINT NOT NULL,
    shortNull SMALLINT NOT NULL,
    intNotNull INTEGER NOT NULL,
    intNull INTEGER NOT NULL,
    longNotNull INTEGER NOT NULL,
    longNull INTEGER NOT NULL,
    floatNotNull FLOAT NOT NULL,
    floatNull FLOAT NOT NULL,
    doubleNotNull FLOAT NOT NULL,
    doubleNull FLOAT NOT NULL,
    charNotNull CHAR NOT NULL,
    charNull CHAR NOT NULL,
    dateNull DATE NOT NULL,
    stringNull VARCHAR (256) NOT NULL,
    bigDecimal DECIMAL NOT NULL,
    bigInteger INTEGER NOT NULL,
    PrimitiveTypes INTEGER NOT NULL,
    CONSTRAINT PCPNT_PT PRIMARY KEY (ID)
);

-------------------------
-- company
-------------------------

CREATE TABLE companies (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(32) NOT NULL,
    FOUNDEDDATE VARCHAR(32) NOT NULL,
    STREET VARCHAR(64),
    CITY VARCHAR(64),
    STATE CHAR(2),
    ZIPCODE CHAR(5),
    COUNTRY VARCHAR(64),
    CONSTRAINT COMPS_PK PRIMARY KEY (ID)
);

CREATE TABLE departments (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(32) NOT NULL,
    EMP_OF_THE_MONTH INTEGER,
    COMPANYID INTEGER REFERENCES companies,
    CONSTRAINT DEPTS_PK PRIMARY KEY (ID)
);

CREATE TABLE persons (
    PERSONID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    FIRSTNAME VARCHAR(32) NOT NULL,
    LASTNAME VARCHAR(32) NOT NULL,
    MIDDLENAME VARCHAR(32),
    BIRTHDATE VARCHAR(32) NOT NULL,
    STREET VARCHAR(64),
    CITY VARCHAR(64),
    STATE CHAR(2),
    ZIPCODE CHAR(5),
    COUNTRY VARCHAR(64),
    HIREDATE VARCHAR(32) NOT NULL,
    WEEKLYHOURS FLOAT NOT NULL,
    DEPARTMENT INTEGER REFERENCES departments NOT NULL,
    FUNDINGdEPT INTEGER REFERENCES departments NOT NULL,
    MANAGER INTEGER REFERENCES persons NOT NULL,
    MENTOR INTEGER REFERENCES persons NOT NULL,
    HRADVISOR INTEGER REFERENCES persons NOT NULL,
    SALARY FLOAT NOT NULL,
    WAGE FLOAT NOT NULL,
    DISCRIMINATOR varchar(64) NOT NULL,
    CONSTRAINT EMPS_PK PRIMARY KEY (PERSONID)
);

CREATE TABLE insuranceplans (
    INSID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CARRIER VARCHAR(64) NOT NULL,
    LIFETIME_ORTHO_BENEFIT DECIMAL NOT NULL,
    PLANtYPE VARCHAR(8) NOT NULL,
    DISCRIMINATOR VARCHAR(64) NOT NULL,
    EMPLOYEE INTEGER REFERENCES persons,
    CONSTRAINT INS_PK PRIMARY KEY (INSID)
);

CREATE TABLE projects (
    PROJID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(32) NOT NULL,
    BUDGET DECIMAL NOT NULL,
    CONSTRAINT PROJS_PK PRIMARY KEY (PROJID)
);

CREATE TABLE project_reviewer (
    projid INTEGER REFERENCES projects NOT NULL,
    reviewer INTEGER REFERENCES persons NOT NULL
);

CREATE TABLE project_member (
    projid INTEGER REFERENCES projects NOT NULL,
    member INTEGER REFERENCES persons NOT NULL
);

CREATE TABLE employee_phoneno_type (
    empid INTEGER REFERENCES persons NOT NULL,
    phoneno VARCHAR(16) NOT NULL,
    type VARCHAR(16) NOT NULL
);

ALTER TABLE departments (
    ADD CONSTRAINT EMP_MO_FK FOREIGN KEY
        (EMP_OF_THE_MONTH) REFERENCES persons(PERSONID)
);

-------------------------
--fieldtypes
-------------------------

-------------------------
--inheritance
-------------------------

-------------------------
--instancecallbacks
-------------------------

CREATE TABLE ICNonPersistFds (
    ICKEY INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    D DOUBLE,
    S SMALLINT,
    FLOATVAL FLOAT,
    INTVAL INTEGER,
    CONSTRAINT ICNP_PK PRIMARY KEY (ICKEY)
);

CREATE TABLE InstanceCallbacks (
    ICKEY INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(64),
    TIMEDATE TIMESTAMP,
    NEXTOBJ INTEGER,
    CHILD INTEGER,
    INTVAL INTEGER,
    DOUBLEVAL DOUBLE,
    CHILD2DEL INTEGER,
    CHARVAL CHAR(254),
    CONSTRAINT IC_PK PRIMARY KEY (ICKEY)
);

-------------------------
--lifecycle
-------------------------

disconnect;
